/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-limesdr
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LIMESDR_API_H
#define INCLUDED_LIMESDR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_limesdr_EXPORTS
#define LIMESDR_API __GR_ATTR_EXPORT
#else
#define LIMESDR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LIMESDR_API_H */
